using System.Text;

namespace Terminal.Gui.Cli;

/// <summary>
/// Strips terminal escape sequences from untrusted content before it reaches the terminal driver.
/// Removes ESC (\x1b), BEL (\x07), 8-bit CSI (\x9b), 8-bit OSC (\x9d), and C1 7-bit pairs
/// (\x1b@ through \x1b_) to prevent OSC clipboard hijack, window-title rewrite, link spoofing,
/// and other terminal-state abuses.
/// </summary>
public static class TerminalEscapeSanitizer
{
    /// <summary>
    /// Sanitizes user-supplied content by removing dangerous terminal control sequences.
    /// </summary>
    public static string? Sanitize (string? input)
    {
        if (input is null)
        {
            return null;
        }

        if (input.Length == 0)
        {
            return string.Empty;
        }

        StringBuilder? sb = null;

        for (int i = 0; i < input.Length; i++)
        {
            char c = input[i];

            switch (c)
            {
                case '\x1b':
                    sb ??= new StringBuilder (input.Length).Append (input, 0, i);

                    if (i + 1 < input.Length && input[i + 1] >= '@' && input[i + 1] <= '_')
                    {
                        i++;
                    }

                    break;

                case '\x07':
                case '\x9b':
                case '\x9d':
                    sb ??= new StringBuilder (input.Length).Append (input, 0, i);

                    break;

                default:
                    sb?.Append (c);

                    break;
            }
        }

        return sb?.ToString () ?? input;
    }

    /// <summary>
    /// Strips user-payload escape sequences from ANSI renderer output while preserving
    /// legitimate SGR sequences generated by the renderer itself.
    /// </summary>
    public static string SanitizeRenderedOutput (string renderedAnsi)
    {
        if (string.IsNullOrEmpty (renderedAnsi))
        {
            return string.Empty;
        }

        StringBuilder? sb = null;

        for (int i = 0; i < renderedAnsi.Length; i++)
        {
            char c = renderedAnsi[i];

            switch (c)
            {
                case '\x1b':
                    if (i + 1 < renderedAnsi.Length)
                    {
                        char next = renderedAnsi[i + 1];

                        if (next == '[')
                        {
                            sb?.Append ('\x1b');
                            sb?.Append ('[');
                            i += 2;

                            while (i < renderedAnsi.Length)
                            {
                                char seqChar = renderedAnsi[i];
                                sb?.Append (seqChar);

                                if (seqChar is >= '@' and <= '~')
                                {
                                    break;
                                }

                                i++;
                            }
                        }
                        else if (next == ']')
                        {
                            if (i + 2 < renderedAnsi.Length && renderedAnsi[i + 2] == '8')
                            {
                                sb?.Append ('\x1b');
                                sb?.Append (']');
                                i += 2;

                                while (i < renderedAnsi.Length)
                                {
                                    char osc = renderedAnsi[i];

                                    if (osc == '\x07')
                                    {
                                        sb?.Append (osc);

                                        break;
                                    }

                                    if (osc == '\x1b' && i + 1 < renderedAnsi.Length && renderedAnsi[i + 1] == '\\')
                                    {
                                        sb?.Append ('\x1b');
                                        sb?.Append ('\\');
                                        i++;

                                        break;
                                    }

                                    sb?.Append (osc);
                                    i++;
                                }
                            }
                            else
                            {
                                sb ??= new StringBuilder (renderedAnsi.Length).Append (renderedAnsi, 0, i);
                                i += 2;

                                while (i < renderedAnsi.Length)
                                {
                                    char osc = renderedAnsi[i];

                                    if (osc == '\x07')
                                    {
                                        break;
                                    }

                                    if (osc == '\x1b' && i + 1 < renderedAnsi.Length && renderedAnsi[i + 1] == '\\')
                                    {
                                        i++;

                                        break;
                                    }

                                    i++;
                                }
                            }
                        }
                        else if (next is >= '@' and <= '_')
                        {
                            sb ??= new StringBuilder (renderedAnsi.Length).Append (renderedAnsi, 0, i);
                            i++;
                        }
                        else
                        {
                            sb ??= new StringBuilder (renderedAnsi.Length).Append (renderedAnsi, 0, i);
                        }
                    }
                    else
                    {
                        sb ??= new StringBuilder (renderedAnsi.Length).Append (renderedAnsi, 0, i);
                    }

                    break;

                case '\x07':
                case '\x9b':
                case '\x9d':
                    sb ??= new StringBuilder (renderedAnsi.Length).Append (renderedAnsi, 0, i);

                    break;

                default:
                    sb?.Append (c);

                    break;
            }
        }

        return sb?.ToString () ?? renderedAnsi;
    }
}
