<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <OutputType>Exe</OutputType>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Clet.ConfigTests</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="xunit.v3" Version="2.0.2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../../src/Clet/Clet.csproj" />
        <ProjectReference Include="../../src/Terminal.Gui.Cli/Terminal.Gui.Cli.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

</Project>